type Query {
  getAllClassrooms: [Classroom]
  getClassroomById(classroomId: ID): Classroom
  getClassroomsByInstructorId(instructorID: String): [Classroom]
  getClassroomsByStudentIds(studentId: String!): [Classroom]
  getAttendance(minDate: String!, maxDate: String): [Attendance]

  getLectureById(id: String!): Lecture
  listLectures: [Lecture]
  getLectureByInstructorId(id: ID): [Lecture]!
  getLectureByTopic(topic: String!): [Lecture]

  getStudentNotes(lectureId: String!, studentId: String!, classroomId: String!): StudentNotes
}
type Mutation {
  createClassroom(description: String!, classroomName: String!, instructorIds: [String]): Classroom
  addStudentsInClassRoom(studentIds: [String]!, classroomId: String!): Classroom
  addLectureInClassRoom(lectureId: String!, classroomId: String!): Classroom
  addInstructor(instructorId: String!, classroomId: String!): Classroom
  #    attendance

  createLecture(
    instructorId: String!
    classroomId: String!
    topics: [String!]!
    notes: String
    testIds: [String]
    lectureName: String!
    lectureDescription: String! 
  ): Lecture!

  updateTopics(topics: [String]!, lectureId: String!): Lecture!

  updateStudentNotes(
    lectureId: String!
    studentId: String!
    notes: String!
    classroomId: String!
  ): StudentNotes!
}

