type InviteLink {
  link: String!
  expiry: String!
}

type Query {
  getAllClassrooms: [Classroom]
  getClassroomById(classroomId: String!): Classroom
  getClassroomsByInstructorId(instructorID: String): [Classroom]
  getClassroomsByStudentIds(studentId: String!): [Classroom]
  getAttendance(minDate: String!, maxDate: String): [Attendance]
  getLectureById(id: String!): Lecture
  listLectures: [Lecture]
  getLectureByInstructorId(id: ID): [Lecture]!
  getLectureByTopic(topic: String!): [Lecture]
  getStudentNotes(
    lectureId: String!
    studentId: String!
    classroomId: String!  
  ): StudentNotes
  getInviteLink(classroomId: String!): InviteLink
}
type Mutation {
  createClassroom(
    description: String!
    classroomName: String!
    instructorIds: [String]
    organizationId: String
  ): Classroom
  addStudentsInClassRoom(studentIds: [String]!, classroomId: String!): Classroom
  addLectureInClassRoom(lectureId: String!, classroomId: String!): Classroom
  addInstructor(instructorId: String!, classroomId: String!): Classroom
  #    attendance
  createInviteLink(classroomId: String!, expiry: String!): InviteLink
  createLecture(
    instructorId: String!
    classroomId: String!
    topics: [String!]!
    notes: String
    testIds: [String]
    lectureName: String!
    lectureDescription: String!
  ): Lecture!
  updateTopics(topics: [String]!, lectureId: String!): Lecture!
  updateStudentNotes(
    lectureId: String!
    studentId: String!
    notes: String!
    classroomId: String!
  ): StudentNotes!

  joinClassroom(inviteLink: String!, studentId: String!): [Classroom]

  joinClassroomByCode(classroomCode: String!, studentId: String!, organizationId: String!): [Classroom]
}
