spring:
  application:
    name: lecture_management_service

  datasource:
    url: jdbc:postgresql://localhost:5432/learning_platform_lecture_mgmt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: test
      password: test

  graphql:
    graphiql:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath*:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
logging:
  level:
    root: INFO

api:
  services:
    auth:
      baseUrl: 'http://localhost:8081'
      endpoints:
        verifyToken:
          endPointPath: '/auth/api/v1/verifyToken'
          methodType: 'GET'
jwt:
  expiration: 3600
  secret: "GibVa0MF2Wg29IVvY+kRFDf3xG6GVog9V5UocoUab6s="


encryption-key: "e0ec288d28ef0b99d9df6bb51abe59fca34d276d8f9f170e3853c3db216ff085f"

