changeLogFile=src/main/resources/db/changelog/migrations/student-notes-migration.xml
url=jdbc:postgresql://localhost:5432/learning_platform_lecture_mgmt
username=postgres
password=postgres
driver=org.postgresql.Driver 