# Path to the main changelog file
changeLogFile=db/changelog/db.changelog-master.xml

# JDBC driver class
driver=org.postgresql.Driver

# JDBC URL for your database
url=jdbc:postgresql://localhost:5432/learning_platform_lecture_mgmt

# Database credentials
username=postgres
password=postgres
